Fix dynamic import
The `tsconfig.json` change to `module`/`moduleResolution` now causes
the following error:

```
TypeError: A dynamic import callback was invoked without --experimental-vm-modules
```

In other words, we need to use the experimental flag mentioned above
to run tests. However the dynamic import behaviour changed and the format
of the module is now the same for both TS and JS.

NOTE: We use dynamic `import` to dynamically load the Incident Type config
at runtime.

See: https://jestjs.io/docs/next/ecmascript-modules