Document why `checkSession`/`csrf` needs to be `false`
Setting these to `true` also causes some TypeError

```
TypeError: Cannot read properties of undefined (reading 'apply')
```