IR-1574: Use modern `module`/`moduleResolution` (#794)
* Use modern module/moduleResolution

Removed overrides in our `tsconfig.json` files, so
using values coming from extended config (`@tsconfig/node24/tsconfig.json`):
- `module` set to `NodeNext` (was `CommonJs`)
- `moduleResolution` set to `Node16` (was `Node`)

* Fix dynamic import

The `tsconfig.json` change to `module`/`moduleResolution` now causes
the following error:

```
TypeError: A dynamic import callback was invoked without --experimental-vm-modules
```

In other words, we need to use the experimental flag mentioned above
to run tests. However the dynamic import behaviour changed and the format
of the module is now the same for both TS and JS.

NOTE: We use dynamic `import` to dynamically load the Incident Type config
at runtime.

See: https://jestjs.io/docs/next/ecmascript-modules

* tsconfig: Removed redundant options

Both options were set the same way in the `@tsconfig/node24/tsconfig.json`
file so we can safely remove them and keep our config simpler
without any change.

* TS: Compile integration tests to more modern JS

For tests we can transpile to ES2024 as we don't need
to support older platforms.

* npm prune

This shouldn't be necessary in theory but we still had a few
_extraneous_ packages, probably old dependencies:

```
$ npm list | grep extra

├── @apm-js-collab/code-transformer@0.8.2 extraneous
├── @apm-js-collab/tracing-hooks@0.3.1 extraneous
├── @flipt-io/flipt@1.5.0 extraneous
├── @opentelemetry/context-async-hooks@2.5.0 extraneous
├── @opentelemetry/instrumentation-amqplib@0.55.0 extraneous
├── @opentelemetry/instrumentation-connect@0.52.0 extraneous
├── @opentelemetry/instrumentation-dataloader@0.26.0 extraneous
├── @opentelemetry/instrumentation-express@0.57.0 extraneous
├── @opentelemetry/instrumentation-fs@0.28.0 extraneous
├── @opentelemetry/instrumentation-generic-pool@0.52.0 extraneous
├── @opentelemetry/instrumentation-graphql@0.56.0 extraneous
├── @opentelemetry/instrumentation-hapi@0.55.0 extraneous
├── @opentelemetry/instrumentation-http@0.208.0 extraneous
├── @opentelemetry/instrumentation-ioredis@0.56.0 extraneous
├── @opentelemetry/instrumentation-kafkajs@0.18.0 extraneous
├── @opentelemetry/instrumentation-knex@0.53.0 extraneous
├── @opentelemetry/instrumentation-koa@0.57.0 extraneous
├── @opentelemetry/instrumentation-lru-memoizer@0.53.0 extraneous
├── @opentelemetry/instrumentation-mongodb@0.61.0 extraneous
├── @opentelemetry/instrumentation-mongoose@0.55.0 extraneous
├── @opentelemetry/instrumentation-mysql@0.54.0 extraneous
├── @opentelemetry/instrumentation-mysql2@0.55.0 extraneous
├── @opentelemetry/instrumentation-pg@0.61.0 extraneous
├── @opentelemetry/instrumentation-redis@0.57.0 extraneous
├── @opentelemetry/instrumentation-tedious@0.27.0 extraneous
├── @opentelemetry/instrumentation-undici@0.19.0 extraneous
├── @opentelemetry/redis-common@0.38.2 extraneous
├── @opentelemetry/sql-common@0.41.2 extraneous
├── @prisma/instrumentation@6.19.0 extraneous
├── @sentry/core@10.34.0 extraneous
├── @sentry/node-core@10.34.0 extraneous
├── @sentry/node@10.34.0 extraneous
├── @sentry/opentelemetry@10.34.0 extraneous
├── @types/mysql@2.15.27 extraneous
├── @types/pg-pool@2.0.6 extraneous
├── @types/pg@8.15.6 extraneous
├── @types/tedious@4.0.14 extraneous
├── chart.js@3.9.1 extraneous
├── chartjs-chart-matrix@3.0.0 extraneous
├── chartjs-plugin-datalabels@2.2.0 extraneous
├── concurrently@9.2.1 extraneous
├── deeks@3.1.0 extraneous
├── doc-path@4.1.1 extraneous
├── forwarded-parse@2.1.2 extraneous
├── json-2-csv@5.5.10 extraneous
├── nunjucks-date@1.5.0 extraneous
├── pg-int8@1.0.1 extraneous
├── pg-protocol@1.11.0 extraneous
├── pg-types@2.2.0 extraneous
├── postgres-array@2.0.0 extraneous
├── postgres-bytea@1.0.1 extraneous
├── postgres-date@1.0.7 extraneous
├── postgres-interval@1.2.0 extraneous
├── shell-quote@1.8.3 extraneous
├── with-alpha-hex@1.0.6 extraneous
└── zod@4.1.13 extraneous
```

This removes them from the `package-lock.json` file which means they'll
not be installed anymore.

* tsconfig: Removed `experimentalDecorators` setting

AFAICT it's not used and application builds and
tests pass without it.

* Make stability days in renovate config consistent with npmrc min-release-age (T #711)

---------

Co-authored-by: Andrew Lee <1517745+andrewrlee@users.noreply.github.com>